language: node_js;
node_js: 
  - "stable"
install:
  - npm i
cache: 
  directories:
    - "$HOME/.npm"

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE USER sharon WITH PASSWORD 'sharon';" -U postgres
  - npm i
  - npm run create

env:
  global:
    - DATABASE_TEST=postgres://postgres@localhost/test_db
    - SECRET_KEY=chair and table
    - CLOUD_NAME= dqa4bqv5r
    - API_KEY= 255291596917225
    - API_SECRET= dghxJZ55BxK92k3mblIz-vsPGok

script:
  - npm run test 

after_success: npm run coverage